---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$

  - repo: https://github.com/ansible/ansible-lint
    rev: v5.3.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
